version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Verificando Java y Maven..."
      - java -version
      - mvn -version
  pre_build:
    commands:
      - echo "Preparando build..."
  build:
    commands:
      - echo "Compilando todos los módulos Maven....."
      - mvn clean install -DskipTests
  post_build:
    commands:
      - echo "Build completado correctamente"

artifacts:
  files:
    - '**/target/*.jar'


