version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Instalando dependencias..."
      - mvn --version
  pre_build:
    commands:
      - echo "Preparando build..."
  build:
    commands:
      - echo "Construyendo proyecto Maven..."
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo "Build completado"

artifacts:
  files:
    - target/**/*.jar
